### ISSUE TITLE
Set Up GitHub Actions CI Pipeline

### ISSUE THREAD

**Issue by pierre-filliolaud** [pierre-filliolaud/rpn-api-calculator-python#5]
## 🎯 Objective

Create a GitHub Actions workflow to automate the build, test, and Docker packaging process for the FastAPI RPN Calculator project. This pipeline ensures consistent builds and code validation with each push or pull request.

---

### 📁 Workflow Configuration

- [x] Create a `.github/workflows/ci.yml` file
- [x] Define the workflow to trigger on:
  - `push` to `main`
  - `pull_request` to any branch

### ⚙️ Job: Build & Test

- [x] Use `python:3.11` as the base environment
- [x] Checkout code and install Poetry
- [x] Install dependencies and run tests with `pytest`
- [x] Generate test coverage report

```yaml
name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest --cov
```

### 🐳 Job: Docker Build (optional)

- [x] Add Docker build step (for release tagging only)
- [x] Use `docker/build-push-action` to build and optionally push to registry

---

## ✅ Acceptance Criteria

- GitHub Actions pipeline runs on every push/PR
- Tests execute successfully with coverage output
- Poetry dependencies are correctly installed
- Workflow status badge can be added to `README.md`
